### ISSUE TITLE
Command line not working on MacBook Pro 14" apple M1 Pro

### ISSUE THREAD

**Issue by mark1352** [pine64/blisp#13]
MacBook-Pro-4:Blisp_Linux_x86 markjohn$ sudo ./blisp write -c bl70x --reset Pinecilv2_EN.bin
Password:
./blisp: ./blisp: cannot execute binary file
above copied from terminal. Am I going something wrong?

**Comment by gamelaster** [comment]
Building on MacOS works, although, there are still some UART issues which needs to be addressed.

**Comment by River-b** [comment]
> 

Mark,  the linux   pre-made  executable  you downloaded won't work directly on Mac.  
have you tried  @gamelaster  suggestion to build it  in apple  terminal window?   There are instructions on how to do the build  for linux on the main page of this blisp,  I'm wondering if you could try to follow same instructions and it would build and give you a mac  executable?

I was able  to use the  Linux instructions and make a working executable  on ARM  laptop (pinebook pro).  It  took me about 15 minutes.  you could try  same instructions and see how it goes?

**Comment by mark1352** [comment]
So I need to build on my Mac and not use the Linux build

**Comment by River-b** [comment]
according to the other new ticket  that will not work right now.   Someone else tried today on Mac  and  they can  build it . but then it does not work.

**Comment by gamelaster** [comment]
Should be fixed on latest release.
