### ISSUE TITLE
consider authorizing Shields.io

### ISSUE THREAD

**Issue by River-Mochi** [pine64/blisp#24]
by authorizing Shields.io, it increases the rate limit for GitHub requests going through Shields.io. GitHub-related badges are therefore more robust and faster.

Can do it here:  https://img.shields.io/github-auth

I don't know if you have to authorize for each app or if just clicking on that one time takes care of all of them.

**Comment by River-Mochi** [comment]
@gamelaster  needs to authorize  but if everyone does it that is even better, then Shields.io doesn't get rate limited by Github and all the badges will update a little faster and be smoother.

**Comment by gamelaster** [comment]
Done
