### ISSUE TITLE
handshake fail

### ISSUE THREAD

**Issue by s1stematic** [pine64/blisp#27]
i cant do the picecil v2 firmware update.
the handshake allway fail ... can anyone help ? 
![Captura de ecrã 2023-03-24 114835](https://user-images.githubusercontent.com/128807672/227513466-1c5c0798-dbd4-4546-822e-526711de4aac.png)

**Comment by gamelaster** [comment]
Try to connect Pinecil directly to PC, not via any Hub, eventually try on another PC.
