### ISSUE TITLE
Blisp display of Erase and Download  - make it look more like DFU output?

### ISSUE THREAD

**Issue by River-Mochi** [pine64/blisp#33]
when using PineFlash   which is a GUI  wrapper around blisp,  I notice that the  log output for  Pinecil V1 and V2 are different.

I like the way the V1  shows the erasing  and download in the log; I realize it is using DFU  to do this. 
 is it possible  to make the BLISP  show erasing/download output in this same way?

**Attached sample log files:**
[pinecilV1-pineflaash-log.txt](https://github.com/pine64/blisp/files/11174777/pinecilV1-pineflaash-log.txt)
[pinecilV2-pineflash-log.txt](https://github.com/pine64/blisp/files/11174778/pinecilV2-pineflash-log.txt)

![image](https://user-images.githubusercontent.com/97197236/230505205-ab6ecdf4-8706-45a3-90e2-81ac352f8a23.png)

**Comment by River-Mochi** [comment]
> Most people won't have both irons, right?

@robertlipe 
since  some people will only have the newer V2  they won't experience this nicer output from back in DFU  model.
I'm asking to take this great output design that DFU already has  and put it into BLISP  output display. 
this has nothing to do with the two logs.

if it makes it easier to understand, then simply forget  that I attached both logs -it is muddling what  my request is.  Just look at the image of  the output.  I'm asking for BLISP  to  output in this same beautiful way on the Terminal screen when it does the Erase, and the download  from the PC  into the Pinecil. 

Is this something you are able to do Robert?

**Comment by River-Mochi** [comment]
> Not currently because the projectd doesn't build and run on MacOS. It

oic,  even though we have a binary for MacOS  you can't do dev on  a Macbook using the current code?

**Comment by River-Mochi** [comment]
> idea is pre-approved by the release manager, yes, I can help.

I think both Gamiee and Ralim  might own this repo now.  
@gamelaster  and @Ralim    robert says he can help  make the blisp  output look nicer  if the repo  owners pre-approve.  probably a good idea so he doesn't do the work and then it gets rejected.   
I wanted  Blisp  to have that beautiful output  like I see in other   tools like  DFU-util. 

Robert just needs your approvals  to start working on it.

**Comment by Ralim** [comment]
I have no particular opinion either way; to me both are just a progress indication.
I would happily merge a PR that implements the progress bar correctly sized to the terminal (or if it cant decode the sizing falls back to just the progress information).

**Comment by River-Mochi** [comment]
I'm going close this since if it's not something that can be easily done, not worth it for the visual display
