### ISSUE TITLE
Blisp not building on ArchLinux

### ISSUE THREAD

**Issue by NovaViper** [pine64/blisp#5]
I just downloaded the program so I can flash my Pinecil V2 and tried to build it from source but when I run `cmake -DBLISP_BUILD_CLI=ON ..`, I get this error
```
  The source directory

    /home/novaviper/Downloads/blisp-master/vendor/argtable3

  does not contain a CMakeLists.txt file.
```
Then if I try to run the subsequent cmake command, it tells me there's no makefile (assuming because the first cmake command didn't complete successfully).

Here is the Cmake log output:
[CMakeOutput.log](https://github.com/pine64/blisp/files/9976243/CMakeOutput.log)

System information:
Operating System: Arch Linux
KDE Plasma Version: 5.26.3
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.7
Kernel Version: 6.0.7-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i5-8265U CPU @ 1.60GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620
Manufacturer: LENOVO
Product Name: 20NT000GUS
System Version: ThinkPad L390

**Comment by gamelaster** [comment]
Hi @NovaViper, I develop the tool on the Arch 😁 and yes, I forgot to add `git submodule update --init --recursive` to the instructions. Will add it, thanks

**Comment by NovaViper** [comment]
Ah ok, thanks for the info! I got to build 👍🏾
