### ISSUE TITLE
Flashing fails with handshake failed

### ISSUE THREAD

**Issue by FlareFlo** [pine64/blisp#53]
Flashing using the command `blisp write -c bl70x --reset Pinecilv2_EN.bin` fails.

I ensured my device was authentic and validated its ID before attempting to update.
ChipID redacted in output, but matches what debug display shows.
output:
```Sending a handshake...
Handshake successful!
Getting chip info...
BootROM version 1.0.2.7, ChipID: REDACTED
0b / 59200 (0.00%)
4092b / 59200 (6.91%)
8184b / 59200 (13.82%)
12276b / 59200 (20.74%)
16368b / 59200 (27.65%)
20460b / 59200 (34.56%)
24552b / 59200 (41.47%)
28644b / 59200 (48.39%)
32736b / 59200 (55.30%)
36828b / 59200 (62.21%)
40920b / 59200 (69.12%)
45012b / 59200 (76.03%)
49104b / 59200 (82.95%)
53196b / 59200 (89.86%)
57288b / 59200 (96.77%)
59200b / 59200 (100.00%)
Sending a handshake...
Received no response from chip.
Failed to handshake with device.
```

**Comment by gamelaster** [comment]
Try another PC / cable / try Linux. It's known that Windows have problems sometimes.

**Comment by FlareFlo** [comment]
I forgot to mention, i tried that on `6.5.6-arch2-1`, using both front-panel and motherboard USB-C ports, with two different cables :/

**Comment by FlareFlo** [comment]
I tried with a USB-A to USB-C cable and it worked perfectly. Seems my otherwise working ports/cables are behaving weirdly.
