### ISSUE TITLE
Put release Executable

### ISSUE THREAD

**Issue by River-b** [pine64/blisp#7]
@gamelaster  could we get an executable for the Windows and Linux   in Releases section (since you already made them)?

Some people are uncomfortable downloading the Zip or  Tar.gz  from Discord/Chat and prefer to get it directly from Github.  This also allows us to give a direct link to this repo without uploading it to  chat channel and makes sense from a safety point of view.
Once you have Executables up, I could write some instructions for using them. 

Release package Zips needed in the Latest Releases section.

**Comment by River-b** [comment]
I currently have the pre-made  Windows Blisp Zip in Pinecil Wiki  but I don't  like that since anyone can go into Wiki and swap it with something else that is dangerous and just name it  blisp_windows and we might not know for a while. I put it in  Wiki because people could not always get to it in the Discord Pins (they don't have discord) on the T/M bridges. some people did not feel safe downloading from Discord.

If I could link to a premade  Release Zip for windows inside  this Github, then it would be safer for people since  random people can't just put a Release package in here.   

Thank you for all your work on this.

**Comment by gamelaster** [comment]
I will make a release after rework the logging and errors. Will try to do it ASAP.

**Comment by bangom** [comment]
> I will make a release after rework the logging and errors. Will try to do it ASAP.

Let us know please here, when windows binaries are ready on this Github. Thank you.

**Comment by gamelaster** [comment]
Done since v0.0.2.
